# Generated by Django 4.2.11 on 2025-04-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cards',
            new_name='card',
        ),
    ]
